### ISSUE TITLE
Add Missing Options for Master Block

### ISSUE THREAD

**Issue by GamerBest480** [fortellgames/bw_bugtracker#119]
The Master Block is missing three settings in the coding panel that were probably unused or something. They were setting to change the Fog Density, The Gravity effect and the effect for how easily you can make things move freely around. I was hoping you can add those three options back in the revival in the master block again.

Here an image of the three settings if you are confuse on what I meant:

![40AF0301-8AC4-4C98-B409-99C22DE4163D](https://github.com/user-attachments/assets/e05db824-1224-4f5f-ae22-ac063d333b08)

**Comment by cetfen** [comment]
These settings are still ingame.
![TheyreStillInGameYouCandleStick](https://github.com/user-attachments/assets/eb332bce-e5ef-4168-8e50-ac3ab3f03a24)

**Comment by tobyisawesome** [comment]
These settings exist ingame in the current build.

**Comment by GamerBest480** [comment]
Alright I’m glad that those settings were added back in the current build of the revival :)

**Comment by tobyisawesome** [comment]
Maybe close the post?
