### ISSUE TITLE
(MR/VR) Better controller layout for play mode

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#132]
![Better Quest button layout](https://github.com/user-attachments/assets/cb51cf03-e1ad-4aed-9aa6-eeaaa6a1d3c8)

Left controller stick should be using the WASD controls from PC.
Right controller stick should be the arrow keys buttons from PC
L and R should be B and A.
Triggers should be reserved for grabbing objects.

**Comment by dianateper** [comment]
Fixed in latest version

**Comment by Aktion** [comment]
@DaviveCZ please confirm

**Comment by DaviveCZ** [comment]
oh this controller layout? this has been fixed a long time ago! :D
