### ISSUE TITLE
(MR/VR) Bug when deselecting block mid-rotation.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#134]
This bug likely causes when deselecting the block while it's rotating.

https://github.com/user-attachments/assets/53263c19-a014-494d-8500-24c681ee8b37

**Comment by DaviveCZ** [comment]
also it causes everything to be unselectable. it fixes itself when going to play mode and back to build mode

**Comment by dianateper** [comment]
Fixed in latest version

**Comment by Aktion** [comment]
@DaviveCZ please check

**Comment by DaviveCZ** [comment]
This appears to no longer happen
