### ISSUE TITLE
(MR/VR) Unable to delete world

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#138]
i'm unable to interact with the UI element for removing world.
the one that asks me if i REALLY wanna delete it.

**Comment by Aktion** [comment]
Screen shot?

**Comment by DaviveCZ** [comment]
![image](https://github.com/user-attachments/assets/b69a9f39-12e6-4e85-822a-afa5f91b7bed)
This UI element
