### ISSUE TITLE
(MR/VR) Unable to type text.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#139]
Game is lacking some type of virtual keyboard for things where you insert name of things or for text.

**Comment by DaviveCZ** [comment]
This is mainly problem in these
![image](https://github.com/user-attachments/assets/bdbf00d2-a408-4f02-ab7f-32930bd5a570)
![image](https://github.com/user-attachments/assets/9cfddce8-f489-4779-a567-64a2b0a3bf9f)

**Comment by Aktion** [comment]
@DaviveCZ is it still exists?

**Comment by DaviveCZ** [comment]
nope. this was fixed with the addition of a keyboard opening up when pressing on Text Input Fields.
However the keyboard does have issue sometimes closing. that was reported as well.

**Comment by Aktion** [comment]
OK im closing this but remain open as #173 is reported
