### ISSUE TITLE
(MR/VR) Scale and Rotate gizmo should scale and stretch with block

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#141]
To make working with bigger things easier.
or perhaps make the laser pointer focus more on the gizmos than the block itself.
![image](https://github.com/user-attachments/assets/9bb62b92-85ec-45a6-9695-f5e90ef8e749)

**Comment by Aktion** [comment]
@DaviveCZ is it still here?

**Comment by DaviveCZ** [comment]
it no longer looks small as it was on the picture when its long like that. its fixed
