### ISSUE TITLE
after Playtest Update still not working the new bug can't copy paste

### ISSUE THREAD

**Issue by Broned** [fortellgames/bw_bugtracker#145]
![image](https://github.com/user-attachments/assets/1e3c88ad-2fb0-4720-81c9-d1a864a0b5c9)

**Comment by ronald112** [comment]
@Broned Hi, thanks for bug report. Can you provide us with a video example? We cannot reproduce the bug. 

https://github.com/user-attachments/assets/b7811b90-365f-4f8f-9a81-459d91b75462

**Comment by cetfen** [comment]
Got some footage of this bug, the "Looks like you're out of this type of block." error only shows up when attempting to copy a texture from the sidebar. Copying a color or model from the sidebar appears to not work at all.

https://github.com/user-attachments/assets/30a9c1c4-f705-4593-bb3a-9013455e2d6e
