### ISSUE TITLE
UI scaling bug (iOS alpha)

### ISSUE THREAD

**Issue by Pyronome67** [fortellgames/bw_bugtracker#147]
I’m testing on a 2023 iPad Air and the buttons are super small.  It’s workable but doesn’t make for an overly enjoyable building experience.  In addition the [show log] function is right over the undo and redo button.  
![IMG_2088](https://github.com/user-attachments/assets/dd4b1ed2-48d7-40a1-92e7-51155c95785a)

**Comment by JungleMU** [comment]
This bug is also highly noticeable on iPhone too.

**Comment by DaviveCZ** [comment]
![image](https://github.com/user-attachments/assets/0d021859-feab-4f52-a5aa-f5ff98834472)
looks odd on my end too.
iPad 9th gen
model: MK2L3FD/A

**Comment by DaviveCZ** [comment]
Just had a thought about this today.
My guess as to why it's happening is cos the screen resolution was lower compare to what it's nowadays. And the game was made for smaller screen resolutions in mind. Correct me if i'm wrong.

**Comment by tobyisawesome** [comment]
Due to scaling issues on the iPhone version, it is impossible to drag blocks from the build panel, since they are rendered outside
of the clickable area of the build panel.
