### ISSUE TITLE
(MR/VR) Blocks are missaligned with the room in terms of rotation.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#150]
For some reason before i could align the block with my bed but now it's not possible.
This needs to be fixed, i found in Fortell's other game Holotank it worked better and blocks in that game alligned with the room better.
![image](https://github.com/user-attachments/assets/3a47e405-4113-48b4-b389-8dd1c39d433b)

**Comment by Aktion** [comment]
@DaviveCZ is it any chance that might be related to #163 ? Ie room rotates. In holotanks we allow to manually align if you remember.

**Comment by DaviveCZ** [comment]
absolutely since the world rotation is based on the boundary rotation/position

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (94)

**Comment by Aktion** [comment]
@DaviveCZ please check when you have an opportunity, and close if ok

**Comment by DaviveCZ** [comment]
Yup. this works. i checked the scenarios where making new boundaries would break this and all seems to work fine.
It no longer missalignes when making new boundaries.
