### ISSUE TITLE
(MR/VR) Could not paste model.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#154]
Similar bug that's happening on PC is also happening here as well.
This happened on this block in particular once i placed 4 of the same blocks. Couldn't paste 5th one.
This happens on larger models as well that feature more blocks.
![image](https://github.com/user-attachments/assets/d74e935d-4b79-4f49-bc0b-69a05ac66f6a)

**Comment by Aktion** [comment]
Is it still exist @DaviveCZ ?

**Comment by DaviveCZ** [comment]
Last time i played the game. This issue has been fixed.
I remember testing if this still happens after 5th copied object and it no longer seem to happens.
