### ISSUE TITLE
(MR/VR) Page scrolling issue for Build Main Menu UI

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#158]
It's difficult to scroll upwards in this Menu. The way i could see this being fixed is if the scroll bar on the right side would be made bigger.
This similar issue is on PC as well but less annoying.

https://github.com/user-attachments/assets/c59d30e7-5e19-4c24-8748-7464a3824018

**Comment by tobyisawesome** [comment]
This is a bug, not a feature request.
