### ISSUE TITLE
(MR/VR) Position of things is wrong after boundary is recreated

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#163]
I placed 2 models in this corner of the room.
![image](https://github.com/user-attachments/assets/9c6915cb-3942-4085-8fbc-2557c97963e7)

Recreated the roomscale boundary by redrawing it differently than before. And i'm unable to find these two models where i last placed them.
![image](https://github.com/user-attachments/assets/8693b698-0090-4610-b930-a1b3b2b57f01)

They ended up being somewhere else...
![image](https://github.com/user-attachments/assets/5c41b199-ed9d-4380-be22-22b16933e2d4)

Please make it where it's similar to Holotanks where the game remembers where things were placed cos the way it was done in there was good. especially considering it worked well there with multiple rooms and all i just had to do is load different battlefield that has the layout made for that room.

**Comment by Aktion** [comment]
@DaviveCZ, does it still exist?

**Comment by DaviveCZ** [comment]
Yup it's still in the game. The world's position is dependand on how the boundaries are set up instead of how the room is set up.
When testing the ceiling and floor but i noticed the train track i made was half inside my shelves. Again, this should be like in Holotanks where it remembers where things are in the room.

**Comment by Aktion** [comment]
@DaviveCZ - still here?

**Comment by DaviveCZ** [comment]
this is fixed and no longer happens when i try to reproduce it the way i described. but we still need a way to set world's center in the room manually.
