### ISSUE TITLE
(MR/VR) pointing at action panel needs better laser pointer

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#166]
Currently when you aim at Action Panel, there's no indication of what you're actually pointing at.
This could be easily fixed by either making the laser pointer line extend towards the action panel or make it where there's a dot/cursor shown on where you're pointing at. Just some QoL thing.

**Comment by Aktion** [comment]
@DaviveCZ btw do we need a shortcut button to reveal/hide actions panel?

**Comment by DaviveCZ** [comment]
not really. we just need a laser pointer to indicate what you're actually pointing at to not accidentally grab the wrong action from distance. But if you were to add a button to hide the UI element. i would add it as a physical button on the Action Panel UI that you point at and press.

**Comment by Aktion** [comment]
Sometimes I see action panel somewhere far away, especially if you change the global scale to big one and I'm unable to reach it by walking there

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (93)

**Comment by Aktion** [comment]
@DaviveCZ please confirm

**Comment by DaviveCZ** [comment]
it's good now. the circle that shows up when you point at a thing helps a ton!
