### ISSUE TITLE
(MR/VR) Main menu appears pixelated

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#167]
Compare to anything else in the game, the main menu looks pixelated from a distance.
But considering the game will eventually have a redesigned UI, this could be easily fixed by that.
But i'm also wondering how come the UI element here appears to be pixelated more than the objects themself.
Maybe lack of anti-aliasing?
![image](https://github.com/user-attachments/assets/6c7d6ec3-25cb-409a-82bb-0ce3e791feea)

**Comment by dianateper** [comment]
Fixed in last update 2.0.0.105 (92)

**Comment by Aktion** [comment]
@DaviveCZ please check

**Comment by DaviveCZ** [comment]
It's way better now. more readable and no longer looks jagged
