### ISSUE TITLE
(MR/VR) Issue with keyboard for UI elements.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#173]
When you place down a speech bubble for a block/blockster.
The UI for inserting text appears alongside with Meta's keyboard.
however there a big issue with this that will cause you to be locked into that keyboard UI and there will be no way to get out of it unless you **restart the headset.**
Basically if you try to close down the keyboard, it keeps coming back up. it only happens with the keyboard type that has normal enter key instead of the "checkmark" that replaces the enter key.
This happens on things like the speech bubble text input, World description, Win and lose text and probably even more.
I think the game has a problem to deselect the Text field making the headset think that i still want to input a text.

**Comment by DaviveCZ** [comment]
an update on this. This happens for model description as well.
There's also a bug where sometimes keyboard for title of model or world won't show up and only would show up sometimes after multiple presses, basically what happens is that when i presss the title to edit it, it disappears controllers and then makes them appear back probably trying to switch to meta's keyboard but for some reason fails to do so.

**Comment by DaviveCZ** [comment]
still happens on newer version fyi.
Seems like meta has changed the way keyboard looks like where it's more closer to you and smaller too

**Comment by dianateper** [comment]
Fixed in last update 2.0.0.105 (92)

**Comment by Aktion** [comment]
@DaviveCZ this one is big fix - seems Meta keyboard cannot do multiline so as temp solution, one long description for VR/MR

**Comment by DaviveCZ** [comment]
that's alright. The only way i guess to do this is by making in-game keyboard for this. but for now the keyboard is fine

**Comment by Aktion** [comment]
I was even able to use dictatio on meta quest, works ok!
