### ISSUE TITLE
(MR/VR) Checkmark is missing on texture/decal and color

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#177]
The game has a feature where if you press checkmark on these icons, the next block you place down will have that color and texture/decal.
This works in VR but currently the checkmark showing that it's active is missing.
![image](https://github.com/user-attachments/assets/4c80bc3b-627c-451a-a87d-5ca196cf8664)

**Comment by dianateper** [comment]
Fixed in the latest version

**Comment by Aktion** [comment]
@DaviveCZ please check when you have a opportunity, and close if ok

**Comment by DaviveCZ** [comment]
Checkmarks are there now
