### ISSUE TITLE
(MR/VR) Bed and Table collision appears to be higher than normal.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#186]
Recent update seem to have broke this. "Fake" Furniture isn't visible anymore but seems like there's issue with this.
Also an issue where VR ground is partially visible in the room.
![image](https://github.com/user-attachments/assets/56514fcb-72ef-41c9-ac63-f462d2662175)

In room setup the bed's height is like this. and Table is affected as well. seems the "Storage" furniture isn't affected. Seems like this only affected things that had a model before.
![image](https://github.com/user-attachments/assets/7b216500-2e11-4837-b220-dfcfa4a971e8)

**Comment by Aktion** [comment]
Its might be Meta giving us

**Comment by DaviveCZ** [comment]
recent update fixed it

**Comment by Aktion** [comment]
So all good here? Closing @DaviveCZ ?

**Comment by DaviveCZ** [comment]
yup
