### ISSUE TITLE
(MR/VR) Pressing the home button does nothing.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#189]
Recent update broke this. This doesn't work on model preview and on other user's worlds and in worlds you edit.

**Comment by Aktion** [comment]
related to #224

**Comment by dianateper** [comment]
Fixed in last update 2.0.0.105 (92)

**Comment by Aktion** [comment]
@DaviveCZ please check

**Comment by DaviveCZ** [comment]
It works now
