### ISSUE TITLE
(MR/VR) Floor and Ceiling problem

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#190]
If you hide the real world floor and ceiling. You can't unhide them afterwards meaning you're stuck with VR ground/sky.
This appears to be only problem on floor and ceiling.

**Comment by Aktion** [comment]
@DaviveCZ do you have video?

**Comment by DaviveCZ** [comment]
I don't have a video but it's easy to reproduce on
Version 2.0.0.104
Code Version: 91

What it does is that once you've hidden floor and ceiling, you can't unhide them anymore.

**Comment by DaviveCZ** [comment]
https://github.com/user-attachments/assets/d09107f3-8142-454d-8478-cdc85d7cf5f3

But i did a video for you just in case

**Comment by Aktion** [comment]
@DaviveCZ Do you by any chances have more than one room set up? I see similar behaviour in #230

**Comment by dianateper** [comment]
Fixed in the latest version

**Comment by Aktion** [comment]
@DaviveCZ please check when you have an opportunity and close if ok

**Comment by DaviveCZ** [comment]
this was fixed around November so everything is okay here.
