### ISSUE TITLE
(iOS) No Sound or Music

### ISSUE THREAD

**Issue by GamerBest480** [fortellgames/bw_bugtracker#195]
When playing the iOS playtest, I notice that no music is playing when selecting a world or any other world for that matter. Secondly, whenever I place something down, it usually has some kind of fun sound effect for a different object. But now, no sounds came out whenever object is placed down, nothing. Yes my volume and my sound audio ingame is turned up to 100% and still no sound effect is playing.

https://github.com/user-attachments/assets/cb20efbf-841d-4f1b-a78c-c6fe850a2269

**Comment by Aktion** [comment]
Its known issue and already fixed
