### ISSUE TITLE
Unable to get flat wheels

### ISSUE THREAD

**Issue by SpectreCatalyst** [fortellgames/bw_bugtracker#214]
So from what I can tell from earlier posts here is that you were able to flatten wheels. However I am not able to flatten them for some reason when I tried recreating something from the Heros of Aero worlds. I am not sure if this is a bug or a new feature.

https://github.com/user-attachments/assets/320d5c3d-9c9b-41c0-8a65-c6d606a29231

![IMG_4013](https://github.com/user-attachments/assets/cb7be301-9715-4a07-b4c4-9a529fca27a2)

**Comment by tobyisawesome** [comment]
Duplicate
https://github.com/fortellgames/bw_bugtracker/issues/116
