### ISSUE TITLE
(MR/VR) Worlds with leaderboards are soft locked

### ISSUE THREAD

**Issue by Aktion** [fortellgames/bw_bugtracker#223]
Tapping anywhere does nothing

![photo_2024-09-10_10-42-19](https://github.com/user-attachments/assets/6cff8edd-2e47-4ec3-91d6-eb49e5c76f4d)
![photo_2024-09-10_22-27-27](https://github.com/user-attachments/assets/8684ea8f-0581-4fbd-98b7-87dba5682d75)

**Comment by DaviveCZ** [comment]
I no longer get stuck in this so i think it's fixed.
