### ISSUE TITLE
(MR/VR) walls on-off is not working when more than 1 room/space setup

### ISSUE THREAD

**Issue by Aktion** [fortellgames/bw_bugtracker#230]
Setup 2 rooms
Goto 2nd room
Try turn off wall in the second room - an indicator actually detects and off walls in first room!

https://github.com/user-attachments/assets/a2f9811a-8827-45e6-aabb-e46db408dce9

**Comment by DaviveCZ** [comment]
I have 2 rooms setup. Living room and bedroom

**Comment by Aktion** [comment]
yeah seems bug - work fine with one room

**Comment by dianateper** [comment]
Fixed in last update 2.0.0.105 (92)

**Comment by Aktion** [comment]
@DaviveCZ check on your config please

**Comment by DaviveCZ** [comment]
i'm not sure where to check the config but the in-game settings are all on default since i've never really changed them.
tried looking in the files and couldn't find a config file

**Comment by DaviveCZ** [comment]
this issue while kinda fixed. has another issue where it hides the walls of THIS room but the other room is "visible"
![image](https://github.com/user-attachments/assets/45ea5b3a-0e2b-4167-b65f-aeac992df895)

**Comment by Aktion** [comment]
> this issue while kinda fixed. has another issue where it hides the walls of THIS room but the other room is "visible"
> 
> ![image](https://github.com/user-attachments/assets/45ea5b3a-0e2b-4167-b65f-aeac992df895)
> 
> 

This is sounds like a new issue.

@dianateper can you take a look?

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (93)

**Comment by Aktion** [comment]
@DaviveCZ please check?

**Comment by DaviveCZ** [comment]
This issue has been resolved as of latest version. the thing in the image above no longer happens
