### ISSUE TITLE
Buttons On Mobile (Suggesting/Bug(?))

### ISSUE THREAD

**Issue by SpectreCatalyst** [fortellgames/bw_bugtracker#237]
Hi, so I have noticed that while on mobile the action buttons show on the side of my screen, despite if a button command is used or not. Yes they are unusable but it just clutters the screen and if people want to make say photos in Blocksworld its harder for them to do so.
![IMG_4236](https://github.com/user-attachments/assets/4e9299fa-a814-43bc-8f6c-0750a824874c)
![IMG_0721](https://github.com/user-attachments/assets/16acde4f-d30a-4e95-9cbd-528776faa053)

**Comment by GamerBest480** [comment]
https://github.com/fortellgames/bw_bugtracker/issues/196

Already made a bug report on it :D
