### ISSUE TITLE
(MR/VR) Tank treads glitch out the game when trying to remove them.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#248]
What happens is that when you remove them, the outline stays where it was before and you are unable to spawn new objects.
well you kind of are able to but it would spawn multiple of them and they would be invisible in edit mode.

**Comment by DaviveCZ** [comment]
This only happens when trying to edit the object and removing one of the wheels

https://github.com/user-attachments/assets/c6ccad58-6f12-4b6d-b8df-6a0c05cbad80

**Comment by Aktion** [comment]
Wow what a bug :)

**Comment by DaviveCZ** [comment]
even tho it lags the game any time i press play. 
it's amusing to see so many wheels/objects cluttered in the room

**Comment by Aktion** [comment]
Its physics crash, not surprised but indeed relate to recent scroll fix

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (95)

**Comment by Aktion** [comment]
@DaviveCZ is it still here?

**Comment by DaviveCZ** [comment]
it's fixed. it no longer happens
