### ISSUE TITLE
(MR/VR) Please scale down the Action Panel

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#250]
When making something more complex, The Action Panel is going to be too big.
Or at the very least some option to scale it down. Usually i have the Action Panel close to me and being able to bring it close with Menu button is great.
Just wish it was smaller.

**Comment by Aktion** [comment]
There is task to add open close action panel and resize/move

**Comment by DaviveCZ** [comment]
Is it already in the game or not yet implemented?
cos if it is then i'm not sure how to do it :o

**Comment by Aktion** [comment]
Not yet implemented :) under internal discussion rn but maybe you want to
input?

**Comment by DaviveCZ** [comment]
Well what i just want is that panel to be smaller. it doesn't need to hide and such since i find hiding the panel more for non-VR version. (Where you can just move it out of the screen like it is now)

in MR/VR the panel can be just move away from your view which is great about UI elements in MR/VR.
I think it's just the size of it that i find to be too big. I think only the size could change but that's about it. so far it's great.

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (96)

**Comment by DaviveCZ** [comment]
it's good now! I would also make it where if you press the menu button, it would spawn a bit further away from your face and then it's good i would say. :)

**Comment by DaviveCZ** [comment]
it's good now!
