### ISSUE TITLE
(MR/VR) It's difficult to paint small things in the game.

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#253]
https://github.com/user-attachments/assets/112833ff-a005-403e-aca8-051fd67fa56a

the smaller and smaller things are. it would be hard to paint things.
Which is why i was suggesting for there to be a full on VR mode so i could've used the grips to pinch zoom in similar to PC and Mobile.
Alternatively there could be a tool for the player in MR that has some type of temporary enlargement of the block so it's easy to paint stuff.

**Comment by Aktion** [comment]
@DaviveCZ  its #142 duplicate? Close if so

**Comment by DaviveCZ** [comment]
technically i guess. i think this can be closed with #142 being open
