### ISSUE TITLE
Old keybinds don't work.

### ISSUE THREAD

**Issue by NopeNop3Nop3** [fortellgames/bw_bugtracker#27]
In the new Alpha, keybinds such as Ctrl + Z for undoing actions no longer work.

**Comment by Aktion** [comment]
I need a full list if you can

**Comment by ronald112** [comment]
@NopeNop3Nop3 Ctrl + Z, Ctrl + Y should be fixed now

**Comment by NopeNop3Nop3** [comment]
Issue has returned as of 2.0.0.101

**Comment by ronald112** [comment]
@NopeNop3Nop3 cannot reproduce it in 2.0.0.102. 

https://github.com/fortellgames/bw_bugtracker/assets/43217006/b9caf26b-342b-4eb2-83d3-475fbf16fc01
