### ISSUE TITLE
Water block is invisible, and water is invisible on snow maps when having no texture

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#28]
**Steps to reproduce:**

Find a water cube and drag it out.

It should be invisible.

When using a map with a frozen lake, drag the "no texture" icon onto the ice.

It should be invisible.
![image](https://github.com/fortellgames/bw_bugtracker/assets/71511385/415946d2-e070-496d-8744-0034a6b6dd5a)

**Comment by ronald112** [comment]
@tobyisawesome should be fixed now
