### ISSUE TITLE
Login won't work without platform login

### ISSUE THREAD

**Issue by hannaway07** [fortellgames/bw_bugtracker#29]
This is an issue because all my worlds are saved onto my account which i am trying to log into in the video. Pressing platform login creates a blank account. Trying to link the accounts does not work and gives the error in the second attachment.

https://github.com/fortellgames/bw_bugtracker/assets/138819317/5223b1d5-398c-4dba-b7d7-32d603e4f28e

![Screenshot 2024-05-24 153658](https://github.com/fortellgames/bw_bugtracker/assets/138819317/66f64355-2acc-4638-9c50-e05401e125d0)

**Comment by ronald112** [comment]
@Nintentoad125 should be fixed now
