### ISSUE TITLE
Stop the PC version from frequently softlocking in the menus

### ISSUE THREAD

**Issue by hannaway07** [fortellgames/bw_bugtracker#4]
Usually after opening, whenever you try and select an option (e.g: build) there's a good chance the game just doesn't load whatever you pressed and leaves you on a blank screen.

**Comment by Aktion** [comment]
Video? It might be backend sync?

**Comment by ronald112** [comment]
@Nintentoad125 please, provide a video of such places

**Comment by hannaway07** [comment]
This is fixed as of the latest update in the Alpha so it is no longer an issue.
