### ISSUE TITLE
VR: Pressing play in shared world on Quest causes softlock

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#41]
The game softlocks if you press play while playing a public world. This does not apply to private (editable) worlds. 

https://github.com/fortellgames/bw_bugtracker/assets/71511385/0f5ca35d-ef5b-406a-a212-225eb55ac442

**Comment by Aktion** [comment]
Is it still exists @tobyisawesome  ?

**Comment by tobyisawesome** [comment]
Works now.
