### ISSUE TITLE
VR: Objects not correctly touching ground/MR objects in Quest version

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#42]
While playing in MR, objects slightly hover above the real world ground. See how the figurine touches the ground fully vs the blockster. (The effect is more apparent while actually playing.)
![IMG_2206](https://github.com/fortellgames/bw_bugtracker/assets/71511385/e559c734-867c-490e-8316-15ee7d9dda0c)
Also, ingame objects have a tendency to slightly clip through MR space objects when they are on top.
![IMG_2204](https://github.com/fortellgames/bw_bugtracker/assets/71511385/f985eac5-48be-4ba0-977d-133562280e61)

**Comment by Aktion** [comment]
@tobyisawesome can you confirm its fixed (and related to #228

**Comment by tobyisawesome** [comment]
Unfortunately the blocksters still do not seem to touch the ground.

**Comment by tobyisawesome** [comment]
Fixed
