### ISSUE TITLE
VR: Quest MR furniture is affected by ingame lighting and fog

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#43]
When playing a world, the MR objects (ones you can add to your space in Quest) are affected by ingame lighting, even without walls being hidden. 
![IMG_2208](https://github.com/fortellgames/bw_bugtracker/assets/71511385/29ef3208-53f7-4e3c-b5fd-1ec58527ecf5)

This is reproducible by adding a Master Block and changing the Sky Color and Fog Start to different values.  
[Video Showcase](https://cdn.discordapp.com/attachments/1175426277931491428/1247762781395095592/e01a66a98ea04db58758560e95418351.mov?ex=66613525&is=665fe3a5&hm=e67ce2218fb0c93ac0c137e300e14714f3eee8ec460acde93f896749a92ab026&)

**Comment by Aktion** [comment]
@tobyisawesome video is gone, can you reattach please 
It might be by design shader too

**Comment by tobyisawesome** [comment]
Furniture no longer shows up therefore it is no longer affected by fog.
