### ISSUE TITLE
VR: Quest MR space objects are black textured in worlds.

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#45]
When starting the game, the MR objects are their normal colors, however when inside a world, they are textured completely black.
![IMG_2210](https://github.com/fortellgames/bw_bugtracker/assets/71511385/9fcbd048-5a90-44c0-9a88-2ca7bf4febf3)
(In the image, they are dark blue because of the fog color. Increasing the fog distance reveals that they are black.)
![IMG_2217](https://github.com/fortellgames/bw_bugtracker/assets/71511385/024014b5-d0cb-4ff8-b58e-8d9c75487ea0)

This issue does not consistently occur. I've found from my testing that the furniture can also appear with the correct colors sometimes while playing a world.

**Comment by Aktion** [comment]
@tobyisawesome is it still there?
