### ISSUE TITLE
VR: More complex wall structures cause clipping in Quest MR

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#49]
My basement has stairs in the middle, when I hide the wall i put inside the staircase, the game layer clips through the outer walls beside it.
![IMG_3311](https://github.com/fortellgames/bw_bugtracker/assets/71511385/f5714877-2143-4d52-9e7c-5aaebbf8e383)
![IMG_3310](https://github.com/fortellgames/bw_bugtracker/assets/71511385/a6286194-2e5b-4f36-abcf-959494d12034)

**Comment by dianateper** [comment]
@tobyisawesome Can you provide more detail or an example video?

**Comment by Aktion** [comment]
@tobyisawesome ping here

**Comment by tobyisawesome** [comment]
In further inspection, this seems to because the Quest room scan is unable to handle complex wall structure, my room has a staircase in the middle of it and it was unable to scan it properly. This is intentional as it's just using Meta quest's features.
