### ISSUE TITLE
Moving camera with right mouse button does not work

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#50]
Currently in the latest developer build, clicking and dragging with the right mouse button no longer rotates the camera. Trackpad two-finger drag does not rotate camera either. The only way to move the camera in the editor in this verson is by orbiting around a block. This is in 2.0.0.101
(Video + steps coming soon, I can't test currently)

**Comment by ronald112** [comment]
@tobyisawesome should be fixed now

**Comment by tobyisawesome** [comment]
Fixed
