### ISSUE TITLE
VR: Quest MR furniture not lining up with real world furniture ingame.

### ISSUE THREAD

**Issue by tobyisawesome** [fortellgames/bw_bugtracker#57]
This seems to be a Blocksworld bug and not quest bug, as it appears correctly lined up, but once you enter the game it is misaligned. The floor level is also incorrect.

![image](https://github.com/fortellgames/bw_bugtracker/assets/71511385/e9719e91-c174-45ff-af7a-3d87c1bd245b)

**Comment by tobyisawesome** [comment]
Now working in latest

**Comment by tobyisawesome** [comment]
No longer fixed

**Comment by Aktion** [comment]
@tobyisawesome is it still here? I believe its fixed
