### ISSUE TITLE
List of Bugs I Found

### ISSUE THREAD

**Issue by Hacker-man7** [fortellgames/bw_bugtracker#77]
Some of these might already be mentioned by others, but this is just a bunch of stuff I found on my own. I may update in the future.

- The scroll increment for the build menu is very high, could be a personal preference but maybe lower the scroll amount.

- The build mode camera movement may need some adjusting. When working with smaller builds, the base speed is way too fast and the slower speed (holding control) is a little too slow. Consider making a new speed that is between these two, making that the new base speed and replacing the faster one (holding shift) with the current base.

- The bar at the top of the build menu that has the most recent colour and texture as well as copied models and scripts doesn't work properly. Only the script is draggable, the model complains about not having enough of a colour despite absolutely having enough, and the colour and texture copiers don't work at all.

- Some textures and colours are partially transparent, e.g. all the dark colours are very faint, the 7th row (a teal/aqua colour) is basically invisible.

- In the first section of textures, some of them seem broken, not sure if they're purposefully changed or not, so 'fine' will be as I remember it from the original. Blank, glass, gold and invisible work fine, the warning symbol is extremely transparent, glow is moderately transparent with no pulsing animation, and semi-invisible (icon is dotted outline with the light grey highlight) is invisible even in build mode.

- The shop softlocks the game, can't go to a different page or try to exit, had to Alt+F4. Also, occaisonally, trying to load the build page softlocks. Probably safe to assume this goes with all pages. Note: while testing the previous bug, found that even leaving the world softlocked, left me on a black screen.

- If you publish a world and then update it, both versions will still be in the play section, present examples include 'Escape from CaseOh' and 'Godzilla Model Showcase'.

- The descriptions for worlds and I imagine also models (can't test because shop softlocks) are broken. When writing them, all the text appears on one line, having to scroll through with the arrow keys to see the whole thing. When published, the text does wrap, but if the description is too long it just gets cut off at the end of the box.

- Volume sliders in settings don't seem to do anything.

**Comment by tobyisawesome** [comment]
Please make sure to make different posts for each bug and close this one.
