### ISSUE TITLE
Opening shop softlocks game (Steam)

### ISSUE THREAD

**Issue by nezzled** [fortellgames/bw_bugtracker#79]
Expected behavior:
I don't expect the shop to load yet, but it should at least allow you to navigate out once you've entered it.
Received behavior:
The UI elements become unresponsive and the game requires a restart.
Reproduction steps:
Open the shop normally
![image](https://github.com/user-attachments/assets/0d1f3fe6-3345-4b7d-9211-d2bcceecd00a)
(None of the buttons here do anything)

**Comment by ronald112** [comment]
@nezzled models page should work now
problem was with a broken model metadata uploaded by some player
in the next upd there will be an additional check for this
