### ISSUE TITLE
Published worlds having multiple available versions

### ISSUE THREAD

**Issue by Hacker-man7** [fortellgames/bw_bugtracker#91]
If you publish a world and then update it, both versions will still be in the play section, present examples include 'Escape from CaseOh' and 'Godzilla Model Showcase'.

https://github.com/user-attachments/assets/5244b032-0ebe-44e9-b9be-9b5888914a3a

**Comment by ronald112** [comment]
closed as a [duplicate](https://github.com/fortellgames/bw_bugtracker/issues/104)
