### ISSUE TITLE
Build mode camera speed (with fix suggestion)

### ISSUE THREAD

**Issue by Hacker-man7** [fortellgames/bw_bugtracker#93]
The build mode camera movement may need some adjusting. When working with smaller builds, the base speed is way too fast and the slower speed (holding control) is a little too slow. Consider making a new speed that is between these two, making that the new base speed and replacing the faster one (holding shift) with the current base.

https://github.com/user-attachments/assets/782ab42e-4ab8-4786-ab36-6d66b2b07261

**Comment by ronald112** [comment]
closed as a [duplicate](https://github.com/fortellgames/bw_bugtracker/issues/67)
