### ISSUE TITLE
Page scrolling too far (could be personal)

### ISSUE THREAD

**Issue by Hacker-man7** [fortellgames/bw_bugtracker#95]
The scroll increment for block pages in the build menu is very high, could be a personal preference but maybe lower the scroll amount.

https://github.com/user-attachments/assets/a2884659-644e-4ece-b11b-0287e77eebcf

**Comment by Gallop888** [comment]
I agree. I think it should be more customizable.

**Comment by Aktion** [comment]
Thanks
As i mentioned controls was reworked and something may be broken.

**Comment by ronald112** [comment]
closed as a [duplicate ](https://github.com/fortellgames/bw_bugtracker/issues/66 )
